version: '3.8'

services:
  legonizer4-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./config.json:/app/config.json
    environment:
      - LEGONIZER_API_HOST=0.0.0.0
      - LEGONIZER_API_PORT=8000
      - LEGONIZER_DEVICE=cuda
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for caching (future enhancement)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Optional: PostgreSQL for metadata storage (future enhancement)
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: legonizer4
      POSTGRES_USER: legonizer
      POSTGRES_PASSWORD: legonizer_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data:
